from __future__ import annotations

import argparse
from pathlib import Path

from config import load_settings
from fetchers import fetch_sales_data, SalesFetchParams
from transform import (
    to_dataframe,
    build_kpis,
    revenue_by_day,
    revenue_by_channel,
    top_products,
)
from report_excel import build_excel_report
from emailer import send_email_with_attachment
from utils import ensure_outputs_dir, utc_now_iso


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Automated Business Reporting System")
    parser.add_argument("--start", required=True, help="Start date (YYYY-MM-DD)")
    parser.add_argument("--end", required=True, help="End date (YYYY-MM-DD)")
    parser.add_argument(
        "--send-email",
        action="store_true",
        help="Send report via email (requires SMTP settings)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    settings = load_settings()

    raw_data = fetch_sales_data(
        base_url=settings.api_base_url,
        api_key=settings.api_key,
        timeout_seconds=settings.api_timeout_seconds,
        params=SalesFetchParams(start_date=args.start, end_date=args.end),
    )

    df = to_dataframe(raw_data)
    kpis = build_kpis(df)

    daily_df = revenue_by_day(df)
    channel_df = revenue_by_channel(df)
    products_df = top_products(df, n=10)

    outputs_dir = ensure_outputs_dir()
    report_path = outputs_dir / f"business_report_{args.start}_to_{args.end}.xlsx"

    build_excel_report(
        output_path=report_path,
        kpis=kpis,
        df_daily=daily_df,
        df_channel=channel_df,
        df_products=products_df,
    )

    print(f"[OK] Report created: {report_path} at {utc_now_iso()}")

    if args.send_email:
        send_email_with_attachment(
            smtp_host=settings.smtp_host,
            smtp_port=settings.smtp_port,
            username=settings.smtp_username,
            password=settings.smtp_password,
            email_from=settings.email_from,
            email_to=settings.email_to,
            subject=f"Business Report {args.start} → {args.end}",
            body="Attached is your automated business report generated by Python.",
            attachment_path=Path(report_path),
        )
        print("[OK] Email sent successfully.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
